# Generated by Django 4.2.7 on 2023-12-03 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTiendaBicicletas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesorio',
            old_name='nombre',
            new_name='tipo',
        ),
    ]
