# Generated by Django 4.2.7 on 2023-12-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTiendaBicicletas', '0002_rename_nombre_accesorio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='descripcion',
            field=models.TextField(max_length=100),
        ),
    ]
